version: '3.9'

services:
  drupal:
    build:
      context: .
    ports:
      - "8081:80"
    volumes:
      - ./.data/./drupal/modules:/var/www/html/modules
      - ./.data/./drupal/profiles:/var/www/html/profiles
      - ./.data/./drupal/themes:/var/www/html/themes
      - ./.data/./drupal/sites:/var/www/html/sites
    depends_on:
      - database

  database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - ./.data/mariadb:/var/lib/mysql
